package analysis.model;

public class AnswerValue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer_value.id
     *
     * @mbggenerated Tue May 16 15:54:52 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer_value.indicator_id
     *
     * @mbggenerated Tue May 16 15:54:52 CST 2017
     */
    private String indicatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer_value.option_id
     *
     * @mbggenerated Tue May 16 15:54:52 CST 2017
     */
    private String optionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer_value.answer_id
     *
     * @mbggenerated Tue May 16 15:54:52 CST 2017
     */
    private String answerId;


    private Options option;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer_value.id
     *
     * @return the value of answer_value.id
     *
     * @mbggenerated Tue May 16 15:54:52 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer_value.id
     *
     * @param id the value for answer_value.id
     *
     * @mbggenerated Tue May 16 15:54:52 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer_value.indicator_id
     *
     * @return the value of answer_value.indicator_id
     *
     * @mbggenerated Tue May 16 15:54:52 CST 2017
     */
    public String getIndicatorId() {
        return indicatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer_value.indicator_id
     *
     * @param indicatorId the value for answer_value.indicator_id
     *
     * @mbggenerated Tue May 16 15:54:52 CST 2017
     */
    public void setIndicatorId(String indicatorId) {
        this.indicatorId = indicatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer_value.option_id
     *
     * @return the value of answer_value.option_id
     *
     * @mbggenerated Tue May 16 15:54:52 CST 2017
     */
    public String getOptionId() {
        return optionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer_value.option_id
     *
     * @param optionId the value for answer_value.option_id
     *
     * @mbggenerated Tue May 16 15:54:52 CST 2017
     */
    public void setOptionId(String optionId) {
        this.optionId = optionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer_value.answer_id
     *
     * @return the value of answer_value.answer_id
     *
     * @mbggenerated Tue May 16 15:54:52 CST 2017
     */
    public String getAnswerId() {
        return answerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer_value.answer_id
     *
     * @param answerId the value for answer_value.answer_id
     *
     * @mbggenerated Tue May 16 15:54:52 CST 2017
     */
    public void setAnswerId(String answerId) {
        this.answerId = answerId;
    }

    public Options getOption(){
        return option;
    }

    public void setOption(Options option){
        this.option=option;
    }
}