package analysis.model;

import java.util.List;

public class Docset {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docset.id
     *
     * @mbggenerated Tue Apr 11 10:21:41 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docset.docset_name
     *
     * @mbggenerated Tue Apr 11 10:21:41 CST 2017
     */
    private String docsetName;

    private List<Document> documents;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docset.remarks
     *
     * @mbggenerated Tue Apr 11 10:21:41 CST 2017
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docset.id
     *
     * @return the value of docset.id
     *
     * @mbggenerated Tue Apr 11 10:21:41 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docset.id
     *
     * @param id the value for docset.id
     *
     * @mbggenerated Tue Apr 11 10:21:41 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docset.docset_name
     *
     * @return the value of docset.docset_name
     *
     * @mbggenerated Tue Apr 11 10:21:41 CST 2017
     */
    public String getDocsetName() {
        return docsetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docset.docset_name
     *
     * @param docsetName the value for docset.docset_name
     *
     * @mbggenerated Tue Apr 11 10:21:41 CST 2017
     */
    public void setDocsetName(String docsetName) {
        this.docsetName = docsetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docset.remarks
     *
     * @return the value of docset.remarks
     *
     * @mbggenerated Tue Apr 11 10:21:41 CST 2017
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docset.remarks
     *
     * @param remarks the value for docset.remarks
     *
     * @mbggenerated Tue Apr 11 10:21:41 CST 2017
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public List<Document> getDocuments(){
        return documents;
    }

    public void setDocuments(List<Document> documents){
        this.documents=documents;
    }
}