package analysis.model;

import java.util.Date;

public class Document {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document.id
     *
     * @mbggenerated Sat Apr 15 10:18:32 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document.docname
     *
     * @mbggenerated Sat Apr 15 10:18:32 CST 2017
     */
    private String docname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document.docpath
     *
     * @mbggenerated Sat Apr 15 10:18:32 CST 2017
     */
    private String docpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document.remarks
     *
     * @mbggenerated Sat Apr 15 10:18:32 CST 2017
     */
    private String remarks;

    private String docsetid;

    private String indicatorSysId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document.docsetid
     *
     * @mbggenerated Sat Apr 15 10:18:32 CST 2017
     */
    private Docset docset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document.indicator_sys_id
     *
     * @mbggenerated Sat Apr 15 10:18:32 CST 2017
     */
    private IndicatorSys indicatorSys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document.addtime
     *
     * @mbggenerated Sat Apr 15 10:18:32 CST 2017
     */
    private Date addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document.id
     *
     * @return the value of document.id
     *
     * @mbggenerated Sat Apr 15 10:18:32 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document.id
     *
     * @param id the value for document.id
     *
     * @mbggenerated Sat Apr 15 10:18:32 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document.docname
     *
     * @return the value of document.docname
     *
     * @mbggenerated Sat Apr 15 10:18:32 CST 2017
     */
    public String getDocname() {
        return docname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document.docname
     *
     * @param docname the value for document.docname
     *
     * @mbggenerated Sat Apr 15 10:18:32 CST 2017
     */
    public void setDocname(String docname) {
        this.docname = docname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document.docpath
     *
     * @return the value of document.docpath
     *
     * @mbggenerated Sat Apr 15 10:18:32 CST 2017
     */
    public String getDocpath() {
        return docpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document.docpath
     *
     * @param docpath the value for document.docpath
     *
     * @mbggenerated Sat Apr 15 10:18:32 CST 2017
     */
    public void setDocpath(String docpath) {
        this.docpath = docpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document.remarks
     *
     * @return the value of document.remarks
     *
     * @mbggenerated Sat Apr 15 10:18:32 CST 2017
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document.remarks
     *
     * @param remarks the value for document.remarks
     *
     * @mbggenerated Sat Apr 15 10:18:32 CST 2017
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public String getDocsetid(){
        return docsetid;
    }

    public void setDocsetid(String docsetid){
        this.docsetid=docsetid;
    }

    public String getIndicatorSysId(){
        return indicatorSysId;
    }

    public void setIndicatorSysId(String indicatorSysId){
        this.indicatorSysId=indicatorSysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document.docsetid
     *
     * @return the value of document.docsetid
     *
     * @mbggenerated Sat Apr 15 10:18:32 CST 2017
     */
    public Docset getDocset() {
        return docset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document.docsetid
     *
     * @param docset the value for document.docsetid
     *
     * @mbggenerated Sat Apr 15 10:18:32 CST 2017
     */
    public void setDocset(Docset docset) {
        this.docset = docset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document.indicator_sys_id
     *
     * @return the value of document.indicator_sys_id
     *
     * @mbggenerated Sat Apr 15 10:18:32 CST 2017
     */
    public IndicatorSys getIndicatorSys() {
        return indicatorSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document.indicator_sys_id
     *
     * @param indicatorSys the value for document.indicator_sys_id
     *
     * @mbggenerated Sat Apr 15 10:18:32 CST 2017
     */
    public void setIndicatorSys(IndicatorSys indicatorSys) {
        this.indicatorSys = indicatorSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document.addtime
     *
     * @return the value of document.addtime
     *
     * @mbggenerated Sat Apr 15 10:18:32 CST 2017
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document.addtime
     *
     * @param addtime the value for document.addtime
     *
     * @mbggenerated Sat Apr 15 10:18:32 CST 2017
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }
}