package analysis.model;

public class Options {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column options.id
     *
     * @mbggenerated Fri Apr 14 09:56:03 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column options.value
     *
     * @mbggenerated Fri Apr 14 09:56:03 CST 2017
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column options.indicator_id
     *
     * @mbggenerated Fri Apr 14 09:56:03 CST 2017
     */
    private String indicatorId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column options.id
     *
     * @return the value of options.id
     *
     * @mbggenerated Fri Apr 14 09:56:03 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column options.id
     *
     * @param id the value for options.id
     *
     * @mbggenerated Fri Apr 14 09:56:03 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column options.value
     *
     * @return the value of options.value
     *
     * @mbggenerated Fri Apr 14 09:56:03 CST 2017
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column options.value
     *
     * @param value the value for options.value
     *
     * @mbggenerated Fri Apr 14 09:56:03 CST 2017
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column options.indicator_id
     *
     * @return the value of options.indicator_id
     *
     * @mbggenerated Fri Apr 14 09:56:03 CST 2017
     */
    public String getIndicatorId() {
        return indicatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column options.indicator_id
     *
     * @param indicatorId the value for options.indicator_id
     *
     * @mbggenerated Fri Apr 14 09:56:03 CST 2017
     */
    public void setIndicatorId(String indicatorId) {
        this.indicatorId = indicatorId;
    }
}