package analysis.mapper;

import analysis.model.AnswerValue;
import analysis.model.AnswerValueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AnswerValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer_value
     *
     * @mbggenerated Tue May 16 15:54:52 CST 2017
     */
    int countByExample(AnswerValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer_value
     *
     * @mbggenerated Tue May 16 15:54:52 CST 2017
     */
    int deleteByExample(AnswerValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer_value
     *
     * @mbggenerated Tue May 16 15:54:52 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer_value
     *
     * @mbggenerated Tue May 16 15:54:52 CST 2017
     */
    int insert(AnswerValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer_value
     *
     * @mbggenerated Tue May 16 15:54:52 CST 2017
     */
    int insertSelective(AnswerValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer_value
     *
     * @mbggenerated Tue May 16 15:54:52 CST 2017
     */
    List<AnswerValue> selectByExample(AnswerValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer_value
     *
     * @mbggenerated Tue May 16 15:54:52 CST 2017
     */
    AnswerValue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer_value
     *
     * @mbggenerated Tue May 16 15:54:52 CST 2017
     */
    int updateByExampleSelective(@Param("record") AnswerValue record, @Param("example") AnswerValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer_value
     *
     * @mbggenerated Tue May 16 15:54:52 CST 2017
     */
    int updateByExample(@Param("record") AnswerValue record, @Param("example") AnswerValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer_value
     *
     * @mbggenerated Tue May 16 15:54:52 CST 2017
     */
    int updateByPrimaryKeySelective(AnswerValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer_value
     *
     * @mbggenerated Tue May 16 15:54:52 CST 2017
     */
    int updateByPrimaryKey(AnswerValue record);
}