package analysis.mapper;

import analysis.model.DocUseranswer;
import analysis.model.DocUseranswerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DocUseranswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_useranswer
     *
     * @mbggenerated Mon May 15 16:32:15 CST 2017
     */
    int countByExample(DocUseranswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_useranswer
     *
     * @mbggenerated Mon May 15 16:32:15 CST 2017
     */
    int deleteByExample(DocUseranswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_useranswer
     *
     * @mbggenerated Mon May 15 16:32:15 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_useranswer
     *
     * @mbggenerated Mon May 15 16:32:15 CST 2017
     */
    int insert(DocUseranswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_useranswer
     *
     * @mbggenerated Mon May 15 16:32:15 CST 2017
     */
    int insertSelective(DocUseranswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_useranswer
     *
     * @mbggenerated Mon May 15 16:32:15 CST 2017
     */
    List<DocUseranswer> selectByExample(DocUseranswerExample example);
    List<DocUseranswer> selectAllByDocId(String doc_id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_useranswer
     *
     * @mbggenerated Mon May 15 16:32:15 CST 2017
     */
    DocUseranswer selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_useranswer
     *
     * @mbggenerated Mon May 15 16:32:15 CST 2017
     */
    int updateByExampleSelective(@Param("record") DocUseranswer record, @Param("example") DocUseranswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_useranswer
     *
     * @mbggenerated Mon May 15 16:32:15 CST 2017
     */
    int updateByExample(@Param("record") DocUseranswer record, @Param("example") DocUseranswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_useranswer
     *
     * @mbggenerated Mon May 15 16:32:15 CST 2017
     */
    int updateByPrimaryKeySelective(DocUseranswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_useranswer
     *
     * @mbggenerated Mon May 15 16:32:15 CST 2017
     */
    int updateByPrimaryKey(DocUseranswer record);
}