package analysis.mapper;

import analysis.model.Document;
import analysis.model.DocumentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DocumentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document
     *
     * @mbggenerated Sat Apr 15 10:18:32 CST 2017
     */
    int countByExample(DocumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document
     *
     * @mbggenerated Sat Apr 15 10:18:32 CST 2017
     */
    int deleteByExample(DocumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document
     *
     * @mbggenerated Sat Apr 15 10:18:32 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document
     *
     * @mbggenerated Sat Apr 15 10:18:32 CST 2017
     */
    int insert(Document record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document
     *
     * @mbggenerated Sat Apr 15 10:18:32 CST 2017
     */
    int insertSelective(Document record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document
     *
     * @mbggenerated Sat Apr 15 10:18:32 CST 2017
     */
    List<Document> selectByExample(DocumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document
     *
     * @mbggenerated Sat Apr 15 10:18:32 CST 2017
     */
    Document selectByPrimaryKey(String id);

    Document selectAllByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document
     *
     * @mbggenerated Sat Apr 15 10:18:32 CST 2017
     */
    int updateByExampleSelective(@Param("record") Document record, @Param("example") DocumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document
     *
     * @mbggenerated Sat Apr 15 10:18:32 CST 2017
     */
    int updateByExample(@Param("record") Document record, @Param("example") DocumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document
     *
     * @mbggenerated Sat Apr 15 10:18:32 CST 2017
     */
    int updateByPrimaryKeySelective(Document record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document
     *
     * @mbggenerated Sat Apr 15 10:18:32 CST 2017
     */
    int updateByPrimaryKey(Document record);
}