package analysis.mapper;

import analysis.model.Indicator;
import analysis.model.IndicatorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IndicatorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator
     *
     * @mbggenerated Thu Apr 06 15:40:59 CST 2017
     */
    int countByExample(IndicatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator
     *
     * @mbggenerated Thu Apr 06 15:40:59 CST 2017
     */
    int deleteByExample(IndicatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator
     *
     * @mbggenerated Thu Apr 06 15:40:59 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator
     *
     * @mbggenerated Thu Apr 06 15:40:59 CST 2017
     */
    int insert(Indicator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator
     *
     * @mbggenerated Thu Apr 06 15:40:59 CST 2017
     */
    int insertSelective(Indicator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator
     *
     * @mbggenerated Thu Apr 06 15:40:59 CST 2017
     */
    List<Indicator> selectByExample(IndicatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator
     *
     * @mbggenerated Thu Apr 06 15:40:59 CST 2017
     */
    Indicator selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator
     *
     * @mbggenerated Thu Apr 06 15:40:59 CST 2017
     */
    int updateByExampleSelective(@Param("record") Indicator record, @Param("example") IndicatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator
     *
     * @mbggenerated Thu Apr 06 15:40:59 CST 2017
     */
    int updateByExample(@Param("record") Indicator record, @Param("example") IndicatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator
     *
     * @mbggenerated Thu Apr 06 15:40:59 CST 2017
     */
    int updateByPrimaryKeySelective(Indicator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator
     *
     * @mbggenerated Thu Apr 06 15:40:59 CST 2017
     */
    int updateByPrimaryKey(Indicator record);
}