package analysis.mapper;

import analysis.model.IndicatorSys;
import analysis.model.IndicatorSysExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IndicatorSysMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator_sys
     *
     * @mbggenerated Tue Apr 11 10:21:41 CST 2017
     */
    int countByExample(IndicatorSysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator_sys
     *
     * @mbggenerated Tue Apr 11 10:21:41 CST 2017
     */
    int deleteByExample(IndicatorSysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator_sys
     *
     * @mbggenerated Tue Apr 11 10:21:41 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator_sys
     *
     * @mbggenerated Tue Apr 11 10:21:41 CST 2017
     */
    int insert(IndicatorSys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator_sys
     *
     * @mbggenerated Tue Apr 11 10:21:41 CST 2017
     */
    int insertSelective(IndicatorSys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator_sys
     *
     * @mbggenerated Tue Apr 11 10:21:41 CST 2017
     */
    List<IndicatorSys> selectByExample(IndicatorSysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator_sys
     *
     * @mbggenerated Tue Apr 11 10:21:41 CST 2017
     */
    IndicatorSys selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator_sys
     *
     * @mbggenerated Tue Apr 11 10:21:41 CST 2017
     */
    int updateByExampleSelective(@Param("record") IndicatorSys record, @Param("example") IndicatorSysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator_sys
     *
     * @mbggenerated Tue Apr 11 10:21:41 CST 2017
     */
    int updateByExample(@Param("record") IndicatorSys record, @Param("example") IndicatorSysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator_sys
     *
     * @mbggenerated Tue Apr 11 10:21:41 CST 2017
     */
    int updateByPrimaryKeySelective(IndicatorSys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator_sys
     *
     * @mbggenerated Tue Apr 11 10:21:41 CST 2017
     */
    int updateByPrimaryKey(IndicatorSys record);
}