package analysis.mapper;

import analysis.model.Options;
import analysis.model.OptionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OptionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbggenerated Fri Apr 14 09:56:03 CST 2017
     */
    int countByExample(OptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbggenerated Fri Apr 14 09:56:03 CST 2017
     */
    int deleteByExample(OptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbggenerated Fri Apr 14 09:56:03 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbggenerated Fri Apr 14 09:56:03 CST 2017
     */
    int insert(Options record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbggenerated Fri Apr 14 09:56:03 CST 2017
     */
    int insertSelective(Options record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbggenerated Fri Apr 14 09:56:03 CST 2017
     */
    List<Options> selectByExample(OptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbggenerated Fri Apr 14 09:56:03 CST 2017
     */
    Options selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbggenerated Fri Apr 14 09:56:03 CST 2017
     */
    int updateByExampleSelective(@Param("record") Options record, @Param("example") OptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbggenerated Fri Apr 14 09:56:03 CST 2017
     */
    int updateByExample(@Param("record") Options record, @Param("example") OptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbggenerated Fri Apr 14 09:56:03 CST 2017
     */
    int updateByPrimaryKeySelective(Options record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbggenerated Fri Apr 14 09:56:03 CST 2017
     */
    int updateByPrimaryKey(Options record);
}